before_script:
tests:
    stage: test
    script:
        - virtualenv-3.4 env
        - source env/bin/activate
        - pip install -U pip wheel setuptools
        - XDG_CACHE_HOME=/cache bash .travis.sh style
        - XDG_CACHE_HOME=/cache bash .travis.sh tests
        - XDG_CACHE_HOME=/cache bash .travis.sh doctests
    tags:
        - python3
