language: python
python:
    - "3.2"
    - "3.4"
install:
    - pip install -q -r src/requirements.txt
before_script:
    - cd src
    - flake8 --ignore=E128,F403,F401 .
    - python manage.py validate
script:
    - python manage.py test
