language: python
sudo: false
python:
    - "3.4"
install:
    - pip install -U pip wheel setuptools==28.6.1
script:
    - bash .travis.sh $JOB
cache:
    directories:
        - $HOME/.cache/pip
env:
    - JOB=style
    - JOB=doctests
    - JOB=tests-cov
