language: python
python:
    - "3.2"
    - "3.3"
    - "3.4"
install:
    - pip install -q -r src/requirements.txt
before_script:
    - cd src
    - flake8 --ignore=E123,E128,F403,F401,N802,C901 .
    - python manage.py check
    - python manage.py validate
script:
    - coverage run manage.py test
after_success:
    - coveralls
addons:
    sauce_connect:
        username: "tixl"
        access_key:
            secure: "a0NUwGs2jHci0hIg3jySZLkfljv6FP33fZxAyi2gKeaxcVC+a/AailSnUgDoyVWxPr0JnkLvdFcxzDBgrQ1TLsgpRDSXnc1nIGsaHjgvVGSJ1hKACYtO/9QH+dgaaHEsIsHHbvGdnjwjrX8AZtDnkcRk1T3Skj8kUCniaU39w38="
